[2022-12-17T13:44:50.380+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T13:44:47.389880+00:00 [queued]>
[2022-12-17T13:44:50.390+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T13:44:47.389880+00:00 [queued]>
[2022-12-17T13:44:50.390+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T13:44:50.390+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-17T13:44:50.390+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T13:44:50.406+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 13:44:47.389880+00:00
[2022-12-17T13:44:50.411+0000] {standard_task_runner.py:55} INFO - Started process 22567 to run task
[2022-12-17T13:44:50.414+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T13:44:47.389880+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmp8p5onyiz']
[2022-12-17T13:44:50.415+0000] {standard_task_runner.py:83} INFO - Job 86: Subtask proceso
[2022-12-17T13:44:50.550+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T13:44:47.389880+00:00 [running]> on host 26302dc28230
[2022-12-17T13:44:50.783+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T13:44:47.389880+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T13:44:47.389880+00:00
[2022-12-17T13:44:51.237+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T13:44:51.255+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpgvxqza4b/b6_8ksad.json
[2022-12-17T13:44:51.260+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpgvxqza4b/f7ht8_fj.json
[2022-12-17T13:44:51.261+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T13:44:51.261+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T13:44:51.261+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=14838', 'data', 'file=/tmp/tmpgvxqza4b/b6_8ksad.json', 'init=/tmp/tmpgvxqza4b/f7ht8_fj.json', 'output', 'file=/tmp/tmpgvxqza4b/prophet_modelkqz0t2xj/prophet_model-20221217134451.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T13:44:51.261+0000] {logging_mixin.py:120} WARNING - 13:44:51 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T13:44:51.261+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T13:44:51.915+0000] {logging_mixin.py:120} WARNING - 13:44:51 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T13:44:51.915+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T13:44:52.327+0000] {logging_mixin.py:120} INFO - /opt/***
[2022-12-17T13:44:52.328+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 31, in proceso
    outputpath = os.path.join(dirpath,'outpt.csv')
NameError: name 'dirpath' is not defined
[2022-12-17T13:44:52.336+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T134447, start_date=20221217T134450, end_date=20221217T134452
[2022-12-17T13:44:52.359+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 86 for task proceso (name 'dirpath' is not defined; 22567)
[2022-12-17T13:44:52.394+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T13:44:52.415+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
