[2022-12-17T14:18:13.385+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:18:10.527798+00:00 [queued]>
[2022-12-17T14:18:13.394+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:18:10.527798+00:00 [queued]>
[2022-12-17T14:18:13.394+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:18:13.394+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-12-17T14:18:13.394+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-17T14:18:13.409+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): proceso> on 2022-12-17 14:18:10.527798+00:00
[2022-12-17T14:18:13.414+0000] {standard_task_runner.py:55} INFO - Started process 24689 to run task
[2022-12-17T14:18:13.417+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'superforecast_v1', 'proceso', 'manual__2022-12-17T14:18:10.527798+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/predsuper_dag.py', '--cfg-path', '/tmp/tmpjd3rvhdc']
[2022-12-17T14:18:13.418+0000] {standard_task_runner.py:83} INFO - Job 92: Subtask proceso
[2022-12-17T14:18:13.481+0000] {task_command.py:376} INFO - Running <TaskInstance: superforecast_v1.proceso manual__2022-12-17T14:18:10.527798+00:00 [running]> on host 26302dc28230
[2022-12-17T14:18:13.710+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=doloresferrando@gmail.com
AIRFLOW_CTX_DAG_OWNER=super
AIRFLOW_CTX_DAG_ID=superforecast_v1
AIRFLOW_CTX_TASK_ID=proceso
AIRFLOW_CTX_EXECUTION_DATE=2022-12-17T14:18:10.527798+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-17T14:18:10.527798+00:00
[2022-12-17T14:18:14.124+0000] {forecaster.py:927} INFO - Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
[2022-12-17T14:18:14.146+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpxex6ckh1/t9t2mvfq.json
[2022-12-17T14:18:14.154+0000] {filesystem.py:123} DEBUG - input tempfile: /tmp/tmpxex6ckh1/tv9ke0rn.json
[2022-12-17T14:18:14.155+0000] {model.py:1567} DEBUG - idx 0
[2022-12-17T14:18:14.155+0000] {model.py:1570} DEBUG - running CmdStan, num_threads: None
[2022-12-17T14:18:14.155+0000] {model.py:1580} DEBUG - CmdStan args: ['/home/***/.local/lib/python3.7/site-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=86315', 'data', 'file=/tmp/tmpxex6ckh1/t9t2mvfq.json', 'init=/tmp/tmpxex6ckh1/tv9ke0rn.json', 'output', 'file=/tmp/tmpxex6ckh1/prophet_modelugert7y1/prophet_model-20221217141814.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
[2022-12-17T14:18:14.156+0000] {logging_mixin.py:120} WARNING - 14:18:14 - cmdstanpy - INFO - Chain [1] start processing
[2022-12-17T14:18:14.156+0000] {model.py:1583} INFO - Chain [1] start processing
[2022-12-17T14:18:14.723+0000] {logging_mixin.py:120} WARNING - 14:18:14 - cmdstanpy - INFO - Chain [1] done processing
[2022-12-17T14:18:14.723+0000] {model.py:1640} INFO - Chain [1] done processing
[2022-12-17T14:18:15.133+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/super.py", line 32, in proceso
    Outp.to_csv(outputpath)
NameError: name 'Outp' is not defined
[2022-12-17T14:18:15.142+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=superforecast_v1, task_id=proceso, execution_date=20221217T141810, start_date=20221217T141813, end_date=20221217T141815
[2022-12-17T14:18:15.155+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 92 for task proceso (name 'Outp' is not defined; 24689)
[2022-12-17T14:18:15.196+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-17T14:18:15.216+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
